import type { CanonicalRegistryRecord } from './agentic-registry.ts';

const observedAt = '2026-08-17';
const evidence = (sourceRef: string) => [{ sourceType: 'library' as const, sourceRef, observedAt, verified: true }];

const ROLE_CATALOG: Array<[string, string]> = [
  ["BSF-01", "Project Controls Agent"],
  ["BSF-02", "Design Document Coordinator"],
  ["BSF-03", "Field Observation Triage Agent"],
  ["BSF-04", "Scientific Literature & Protocol Agent"],
  ["BSF-05", "Laboratory Data Steward"],
  ["BSF-06", "Sustainability & Impact Analyst"],
  ["CMM-01", "Content Strategist"],
  ["CMM-02", "Copywriter & Social Voice Agent"],
  ["CMM-03", "Post Scheduler & Timing Optimizer"],
  ["CMM-04", "Trend & Opportunity Scanner"],
  ["CMM-05", "Community Triage Agent"],
  ["CMM-06", "Engagement Voice Agent"],
  ["CMM-07", "PR & Press Agent"],
  ["CMM-08", "Influencer & Collaboration Research Agent"],
  ["CMM-09", "Campaign Optimization Agent"],
  ["CMO-01", "Artist Operations Orchestrator"],
  ["CMO-02", "Persona Bible Curator"],
  ["CMO-03", "Voice Governor"],
  ["CMO-04", "Creative Director Agent"],
  ["CMO-05", "Quality Gatekeeper"],
  ["CMO-06", "Collaboration Coordinator"],
  ["DAA-01", "Data Steward Agent"],
  ["DAA-02", "Data Quality Monitor"],
  ["DAA-03", "Analytics Insight Agent"],
  ["DAA-04", "Forecast & Scenario Agent"],
  ["DAA-05", "Experiment Analyst"],
  ["DAA-06", "ML Model Operations Agent"],
  ["DAA-07", "AI Output Evaluator"],
  ["DAA-08", "Decision Intelligence Agent"],
  ["FRC-01", "Financial Close Support Agent"],
  ["FRC-02", "Spend & Budget Insight Agent"],
  ["FRC-03", "Revenue Assurance Analyst"],
  ["FRC-04", "Contract Intelligence Agent"],
  ["FRC-05", "Compliance Monitoring Agent"],
  ["FRC-06", "Enterprise Risk Analyst"],
  ["FRC-07", "Privacy & Data-Use Triage Agent"],
  ["FRC-08", "Fraud & Anomaly Triage Agent"],
  ["GKE-01", "Enterprise Workflow Orchestrator"],
  ["GKE-02", "Policy & Control Interpreter"],
  ["GKE-03", "Approval & Delegation Steward"],
  ["GKE-04", "Audit Evidence Curator"],
  ["GKE-05", "Knowledge Base Curator"],
  ["GKE-06", "Research & Source Verification Agent"],
  ["GKE-07", "Records & Retention Coordinator"],
  ["HPE-01", "Care Coordination Support Agent"],
  ["HPE-02", "Clinical Documentation Assistant"],
  ["HPE-03", "Patient/Member Education Writer"],
  ["HPE-04", "Public Program Research Agent"],
  ["HPE-05", "Casework Intake & Routing Agent"],
  ["HPE-06", "Education Content & Assessment Agent"],
  ["CMK-01", "Asset Archivist"],
  ["CMK-02", "Creative Metadata Steward"],
  ["CMK-03", "Rights & Provenance Recorder"],
  ["CMA-01", "Song Strategy Agent"],
  ["CMA-02", "Lyric Composer AI"],
  ["CMA-03", "Lyric Editor & Originality Reviewer"],
  ["CMA-04", "Hook & Recall Tester"],
  ["CMA-05", "Melody & Harmony Generator"],
  ["CMA-06", "Beat & Rhythm Producer"],
  ["CMA-07", "Instrument & Texture Designer"],
  ["CMA-08", "Production Architect"],
  ["CMA-09", "Vocal Direction & Synthesis Agent"],
  ["CMA-10", "Vocal QA Agent"],
  ["CMA-11", "Mix Engineer AI"],
  ["CMA-12", "Mastering Engineer AI"],
  ["CMA-13", "Remix & Format Variations Agent"],
  ["CMA-14", "Audio QA Agent"],
  ["OSP-01", "Operations Planning Agent"],
  ["OSP-02", "Supply & Demand Signal Analyst"],
  ["OSP-03", "Procurement Research & Intake Agent"],
  ["OSP-04", "Vendor Performance Monitor"],
  ["OSP-05", "Process Excellence Agent"],
  ["OSP-06", "Quality Management Agent"],
  ["OSP-07", "Field Service Coordinator"],
  ["OSP-08", "Asset & Maintenance Intelligence Agent"],
  ["PLE-01", "Workforce Planning Agent"],
  ["PLE-02", "Talent Sourcing Research Agent"],
  ["PLE-03", "Learning Experience Designer"],
  ["PLE-04", "Performance Enablement Coach"],
  ["PLE-05", "Employee Service Triage Agent"],
  ["PLE-06", "Organizational Knowledge Facilitator"],
  ["PXD-01", "Product Discovery Agent"],
  ["PXD-02", "Product Requirements Agent"],
  ["PXD-03", "User Research Synthesizer"],
  ["PXD-04", "UX Flow Architect"],
  ["PXD-05", "UI System Designer"],
  ["PXD-06", "Prototype & Experiment Agent"],
  ["PXD-07", "Experience QA Agent"],
  ["CMR-01", "Release Calendar Manager"],
  ["CMR-02", "Release Packager"],
  ["CMR-03", "Metadata & Credits Steward"],
  ["CMR-04", "Rights & Licensing Monitor"],
  ["CMR-05", "Platform Optimization Agent"],
  ["CMR-06", "Playlist & Editorial Pitching Agent"],
  ["CMR-07", "Global Distribution Coordinator"],
  ["CMR-08", "Royalty & Revenue Tracker"],
  ["RCP-01", "Market & Segment Intelligence Agent"],
  ["RCP-02", "Campaign Planner Agent"],
  ["RCP-03", "Sales Research & Account Briefing Agent"],
  ["RCP-04", "Proposal & RFP Response Agent"],
  ["RCP-05", "Customer Success Insight Agent"],
  ["RCP-06", "Support Triage & Knowledge Agent"],
  ["RCP-07", "Voice of Customer Analyst"],
  ["RCP-08", "Partner Ecosystem Research Agent"],
  ["OVL-01", "Insurance Claims Support Agent"],
  ["OVL-02", "Real Estate Transaction Coordinator"],
  ["OVL-03", "Legal Matter Operations Agent"],
  ["OVL-04", "Insurance/Banking Compliance Evidence Agent"],
  ["OVL-05", "Hospitality Guest Experience Agent"],
  ["OVL-06", "Retail Merchandising Insight Agent"],
  ["OVL-07", "Media Rights Operations Agent"],
  ["OVL-08", "Nonprofit Grant Operations Agent"],
  ["ESP-01", "Solution Architecture Agent"],
  ["ESP-02", "Software Implementation Agent"],
  ["ESP-03", "Code Review & Quality Agent"],
  ["ESP-04", "Test Engineering Agent"],
  ["ESP-05", "DevOps & Release Readiness Agent"],
  ["ESP-06", "Reliability Monitor & Incident Triage Agent"],
  ["ESP-07", "Security Posture Analyst"],
  ["ESP-08", "Identity & Access Review Agent"],
  ["ESP-09", "Technical Documentation Agent"],
  ["CMV-01", "Visual Continuity Director"],
  ["CMV-02", "Cover Art & Poster Designer"],
  ["CMV-03", "Cinematic Storyboarding AI"],
  ["CMV-04", "Character & Environment Generator"],
  ["CMV-05", "Motion & Lip-Sync Test Agent"],
  ["CMV-06", "Music Video Generator"],
  ["CMV-07", "Lyric Video & Visualizer Builder"],
  ["CMV-08", "STATIC Lore Agent"],
  ["CMV-09", "Video Editor & Format Optimizer"],
  ["CMV-10", "Visual QA Agent"],
];

const SKILL_CATALOG: Array<[string, string]> = [
  ["SKL-015", "Option & Trade-off Analysis"],
  ["SKL-016", "Qualitative Research Coding"],
  ["SKL-017", "Quantitative Analysis & Visualization"],
  ["SKL-018", "Forecasting & Scenario Modeling"],
  ["SKL-019", "Experiment Design & Interpretation"],
  ["SKL-031", "Data Quality Profiling & Drift Detection"],
  ["SKL-034", "Reconciliation & Variance Analysis"],
  ["SKL-013", "Requirements & Acceptance-Criteria Authoring"],
  ["SKL-014", "Process Mapping & SOP Authoring"],
  ["SKL-020", "Natural-Language Drafting & Adaptation"],
  ["SKL-026", "Code Generation & Secure Implementation"],
  ["SKL-037", "Campaign & Content Planning"],
  ["SKL-043", "Localization & Cultural Adaptation"],
  ["SKL-021", "Tone, Brand & Canon Conformance"],
  ["SKL-022", "Originality & Similarity Risk Review"],
  ["SKL-023", "Accessibility & Plain-Language Review"],
  ["SKL-024", "Design & Visual Continuity Review"],
  ["SKL-025", "Audio Continuity & Technical QA"],
  ["SKL-027", "Code Review & Static-Analysis Interpretation"],
  ["SKL-028", "Test Design & Defect Reproduction"],
  ["SKL-029", "Incident Triage & Runbook Retrieval"],
  ["SKL-030", "Threat Modeling & Security Finding Triage"],
  ["SKL-032", "Model Evaluation & Red-Teaming"],
  ["SKL-036", "Customer/Case Triage & Response Drafting"],
  ["SKL-040", "Release/Delivery Package Validation"],
  ["SKL-042", "Quality Incident & CAPA Support"],
  ["SKL-045", "Evaluation Scorecard & Gate Execution"],
  ["SKL-001", "Structured Intake Normalization"],
  ["SKL-002", "Task Decomposition & Dependency Mapping"],
  ["SKL-003", "Status & Handoff Validation"],
  ["SKL-004", "Approval Routing"],
  ["SKL-041", "Scheduling, Capacity & Route Optimization"],
  ["SKL-044", "Meeting, Decision & Action Capture"],
  ["SKL-006", "Claim Extraction & Source Citation"],
  ["SKL-007", "Source Quality Assessment"],
  ["SKL-008", "Knowledge Retrieval & Grounded Synthesis"],
  ["SKL-009", "Taxonomy & Metadata Tagging"],
  ["SKL-010", "Version, Lineage & Provenance Tracking"],
  ["SKL-033", "Contract & Obligation Extraction"],
  ["SKL-039", "Rights, License & Usage-Restriction Mapping"],
  ["SKL-005", "Policy-to-Control Mapping"],
  ["SKL-011", "Sensitive Data Detection & Redaction"],
  ["SKL-012", "Risk Classification & Escalation"],
  ["SKL-035", "Risk Register & Control Monitoring"],
  ["SKL-038", "Community Safety & Reputation Escalation"],
];

export const AGENT_ROLE_INVENTORY: CanonicalRegistryRecord[] = ROLE_CATALOG.map(([catalogId, name]) => ({
  id: `agent.${catalogId.toLowerCase()}`,
  kind: 'agent',
  name,
  lifecycle: 'active',
  verification: 'VERIFIED',
  health: 'NOT_APPLICABLE',
  dataClassification: 'INTERNAL',
  description: `Canonical role-library inventory record for ${name}.`,
  canonicalRef: `library:skill-catalog:${catalogId}`,
  metadata: { catalogId },
  evidence: evidence('skill-catalog.md'),
}));

export const AGENT_SKILL_INVENTORY: CanonicalRegistryRecord[] = SKILL_CATALOG.map(([catalogId, name]) => ({
  id: `skill.${catalogId.toLowerCase()}`,
  kind: 'skill',
  name,
  lifecycle: 'active',
  verification: 'VERIFIED',
  health: 'NOT_APPLICABLE',
  dataClassification: 'INTERNAL',
  description: `Canonical reusable-skill inventory record for ${name}.`,
  canonicalRef: `library:03_SKILL_AND_INTEGRATION_CATALOG.md#${catalogId}`,
  metadata: { catalogId },
  evidence: evidence('03_SKILL_AND_INTEGRATION_CATALOG.md'),
}));
