import type { CanonicalRegistryRecord } from './agentic-registry.ts';

const observedAt = '2026-08-17';
const accountEvidence = [{ sourceType: 'github' as const, sourceRef: 'Full-Stack-Assets:repository-snapshot:98', observedAt, verified: true }];

const REPOSITORIES: Array<{ name: string; archived?: boolean; defaultBranch?: string }> = [
  { name: "Spyglass-" },
  { name: "evolution-engine" },
  { name: "micro-store-template" },
  { name: "HostGraph-Procurement-Command-Center" },
  { name: "Claude-Repo" },
  { name: "WireandLogic" },
  { name: "COO-Engine-Implementation-" },
  { name: "BeyondMythos.com" },
  { name: "slack-agent-template" },
  { name: "vibe-coding-platform", archived: true },
  { name: "portfolio-publisher" },
  { name: "billion-dollar-brief" },
  { name: "portfolio-hub" },
  { name: "RunwayOS" },
  { name: "mickey-procurement-platform" },
  { name: "TradeQuotePro" },
  { name: "microsaas-starter" },
  { name: "VaporLoop", archived: true },
  { name: "vapor-loop" },
  { name: "VibeCoderz" },
  { name: "nextgengear" },
  { name: "Po" },
  { name: "Squeeze-Candidates-" },
  { name: "LLM-MODEL" },
  { name: "Veritas" },
  { name: "cipherhorizon" },
  { name: "Autonomous-Store" },
  { name: "v0-optimus-the-ai-platform-to-bu" },
  { name: "v0-compute-the-platform-to-build" },
  { name: "HTML" },
  { name: "Photobeam" },
  { name: "cosmo" },
  { name: "Poly-Pipeline" },
  { name: "FullStackAssets" },
  { name: "moviesrule.com" },
  { name: "ios-App", archived: true },
  { name: "SelfLLM" },
  { name: "hostgraph-website-mvp" },
  { name: "vibecoderz-app" },
  { name: "raiseflow" },
  { name: "The-Narrows" },
  { name: "Dropfable.com" },
  { name: "VisionPrompt" },
  { name: "-MoviesRule.com" },
  { name: "Nextgengear.cc" },
  { name: "TheTunerDepot.com" },
  { name: "-Astrokobi.com" },
  { name: "Voice-Generator", archived: true },
  { name: "Slingo-Retro" },
  { name: "Alphamind", archived: true },
  { name: "unreal-engine-skills-for-claude-code-plugin" },
  { name: "EOS-Getting-Started", archived: true },
  { name: "OpenMontage" },
  { name: "CLONER", defaultBranch: "master" },
  { name: "concord" },
  { name: "Keel" },
  { name: "WorldGen" },
  { name: "Podcast-editor-" },
  { name: "astrokobi.online" },
  { name: "astrokobi.site" },
  { name: "astrokobi.space" },
  { name: "The-anti-tourist-guide", archived: true },
  { name: "ANC" },
  { name: "ANCESTOR-SIMULATOR-" },
  { name: "overhead-ar-flight-tracker" },
  { name: "Independence250" },
  { name: "Outfit-Generator" },
  { name: "Fashion-Prompt-Architect" },
  { name: "Influencers-" },
  { name: "Autonomous-Browser" },
  { name: "3d-browser-" },
  { name: "React-browser" },
  { name: "Flash-Browser" },
  { name: "Alexandria" },
  { name: "bbno-llmexperiment" },
  { name: "ForgeCleanAI" },
  { name: "RouteStory", archived: true },
  { name: "DealFlow" },
  { name: "AI-Agentic-Musicians" },
  { name: "Temporal-Drift" },
  { name: "tradewind-dealflow", defaultBranch: "codex/authorized-lead-intake" },
  { name: "Full-Stack-Assets.github.io" },
  { name: "Full-Stack-Assets" },
  { name: "OpportunityOS" },
  { name: "tradewind-autonomous-dealflow" },
  { name: "explorer" },
  { name: "contra-operator" },
  { name: "4dworldbench_code" },
  { name: "VisualScore" },
  { name: "Q-Adapt" },
  { name: "inspatio-world" },
  { name: "AREP" },
  { name: "grok-x-bridge" },
  { name: "grok-operations-control-plane" },
  { name: "BLAIZE-SUNDAY" },
  { name: "blaize-autonomous-producer" },
  { name: "freelancer-oauth-gateway" },
  { name: "buildgraph" },
];

export const GITHUB_REPOSITORY_INVENTORY: CanonicalRegistryRecord[] = REPOSITORIES.map((repository) => ({
  id: `repository.${repository.name.toLowerCase()}`,
  kind: 'repository',
  name: `Full-Stack-Assets/${repository.name}`,
  lifecycle: repository.archived ? 'archived' : 'active',
  verification: 'VERIFIED',
  health: repository.archived ? 'NOT_APPLICABLE' : 'HEALTHY',
  dataClassification: 'INTERNAL',
  description: 'Repository observed directly through the authenticated GitHub account inventory.',
  canonicalRef: `https://github.com/Full-Stack-Assets/${repository.name}`,
  metadata: {
    owner: 'Full-Stack-Assets',
    repositoryName: repository.name,
    defaultBranch: repository.defaultBranch ?? 'main',
    observedAccountSnapshotCount: 98,
  },
  evidence: accountEvidence,
}));
